#!/bin/sh
# @file fuzz.sh
# @author Daniel Starke
# @date 2021-02-06
# @version 2021-02-06
# 
# DISCLAIMER
# This file has no copyright assigned and is placed in the Public Domain.
# All contributions are also assumed to be in the Public Domain.
# Other contributions are not permitted.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

tpl=$(cat <<"_END"
; generated by PrusaSlicer 2.3.0+win64 on 2021-01-30 at 22:02:24 UTC

;
; thumbnail begin 300x150 11880
; iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAik0lEQVR4Ae2dy3MUV5bG6x/ptjH4yU
; MPwOhRIJAEQgghJCHedrex228wGNRtI7AtZMAYjMGIlzECY8DjxTgc4ZiYmInoiYmJCS8c0YtezMKL
; iZiFF73oxSwcMQsvcvJk5a06eevmzZuZ92bezDod8QVu20jCVfnV+X73O5mVarXqyPTqq6/+fOvWrR
; 9A+/fv/3vUv08iFUH9/f2/zszM/PTll1/+x8WLF/8yPDz8f1G/Z2pq6n/ZtQDXhc1/vrKqovIvjY2N
; /QIvKry48CLDi237H4yUrzas7bX2Z4P38/z8/I/wfo5rPPDen52d/S/4vR999NFf6VrIVhXVfxFemO
; np6f+GTxcwL/i0sf0PR8pHJ7atcl4d7LDyZ4P3MJuqwLiSfh1KHvmoEvc3gFHBpxMbi+kThoS1b7DL
; ebC3zfl029POZLXdmp8LpwQwLRNfk64F86ok+U04/8NYrJL/SeXXtg3dzld72pyH+9qdG5PLnD/1P+
; 5s6V2Z+88FH6zwXjUxDbHkoWNqI0WrkuY3Hzhw4G9sLIa/tvUPSTKvfpdZXZ1q96arh65uTS1zzgw/
; 6Rxc+5jTX+3K52fKkDdR8shGlbRfAD5R2JsCfqUXqjV1ftw3q321X2/vXO5cHH3amRlY4rzYu8Tpq/
; Zk+vOwE70kYD2pKHmYV0XHF8FAHj5lCEK2lk6Odjj33SgIRvW1b1gLrmFd2f6M8+HmJ5yjfYucPb1P
; Z/bz4IiWh2lQ8jCnis4vBp9q8CaBF+rQoUP/Q9NW+fWHTaude7tXeCbFG9bV8aXOuZEnnRPulPVW9V
; Fnqmep0Z8F1xV0gfU0PwtMWVQF0quK7i+IISS8YAQhy6vJ/i7nzq6GWUEcZIYFf//6xFIvFp4aetz5
; 4/rHnDd7H3EhfKeRnwU+IBlYt6Vyw1eBKHmkV8XUF6ZWcLk11NfjfDG13DsVxNMV6L5vWDfdk8JLY0
; 87Z134fmJwifP2ukXOKz2POoO9z2r7OSDy4VKzbf+dQATk9ali8ovzpzQEIcshaLGf297mRsGGWT3Y
; VzOsh8iwPt+xzONY57c+5cxuetx5Z8NiLxq+2POYFggPfAjeWyDbWRGfPOhaSKZKFt+EWsHl0uxom3
; PXNaT7vlndR3GQGRb881uuYQHH+sSNhaeHn/CmrGN9jzkH3Wj4XPfjqUwr7h6gLaLkkU6VrL4RtYLL
; obeGOz2gjqMgjoMBw5pa5lxzORa03j/a8qTzgTtlvdu/2DmydpHzRs8jzo4EEB6DdeBWNv+3ChPtIy
; ZXJctvxkNIAvLF0u6BNV6/6h4yq9p0hQzL/f9gZnfdk0NgXADeL4/VYiFUHGDKmnYBPETD13t+62zr
; WaH8/cvWKKfkEV+VPL4pQcjiaXR9txfxvtzdiIKN08EQw3LN7cbkUo9jQSw8i6YsAPAQDV92IfxwxM
; mhiT1AW0TJI54qeX1jagUXRwDZL46v8ED6V9x0heMgb1gwjd10DWt+vBYLoZM1505ZJ90p60/ulHV4
; 7aNe1eEP3Y84G3rF6zsm9wBtEe0jqqtSzfkHoFaw/To7tsLjVhAF8XTVFAf9DhYzLPg9N92p7Np4Ix
; aeceE7TFnH3SnrWN8iLxoCz/pd9+IAhG9FzsMnjyL97Fkpd8MC4X1EagXbpektHd6kxEfB+6I4KDAs
; qDYAeP/Mi4VPefAdiqTelLXhsXo0BJ7FIHwee4C2iKpAcllhWOyFolawXXp+cLULzpd55sOfCvLTVZ
; hhAfcC8A4cC2LhxyNPOafdWPj+xsedmYHFHoCHaAim9Vr3b50je7b+vYh1Bd0iIC+WNYbFREDeDk1s
; WONNR8Ct+Cgogu28YcFEtuBXG274HAta7xfcWAjNdzZlQZkUlqMPVWs861XXtKZfeZ7iUJWAvEjWGR
; aIWsH5amhdj3NlYpk3IYlOBe/HNCwA71d9jgWxEOD7h2jKgj1D6GbBlAU8CyC8zvWdIouqQEFZaVhM
; 1ArOXnAiCJAduBWLgiLD4s2KnRDyhgVdLDAsxrEu+rEQ4Pssm7I8AN+IhsCzeAjf6qLkUZPVhgWiVn
; C2Oj7S7plMWBSUTVcP/X/ODOsOMyzEsSAWwmkhwPc5NGUxAP+WHw1fc01rT/eTzjoyrbqoClQAw2Ii
; CGlehzZ3epAcJiNRFExkWDsbhjXPxULYL4SlaJiyoEw67UfDQ65hMZ61o3upU61WSUitXAUqjGGBCE
; Ka08SGLu92MIxbfRVjupIZ1m2/2sDA+2UWC334PjfEpqxazQEA/OHqoz7P+q1nWiM99jx9xxa1ahWo
; UIYFolawfgFkB0PxuJXkVDCtYQF4/8yvN0AsPOfGQqg4sCkLyqQA4HE0BJ4FEH5T76pC/TfNQq1YBS
; qcYTERhNQjgOwXti9vcCtB5wqbVRLDgpjJwDvjWCwWAnw/haYsqDkwAM+iIfCsF7oWha7vtLpa6Voo
; rGGBqBWcXu9vbQtwq68STFeRhuVXGzDHuritAd+h4vABN2Ud9acsLxr6pdLnu+jkMEytcmvyQhsWE+
; 0jJtPR4Q4vri34FYawKKgUB/0OFm9YC8ywEHgPxEIfvkORFKasE/6UNd3nA3iOZ+3oIQgvU9mrQKUw
; LBA9pSSedg886009MAHhKBg1XcniYJhhsWoD5lgsFkInC+A7P2UBgIflaBwNX/dNK849tFpRZU4epT
; Es9kLRPmK0YO0GzINxK1kUjBMHZYaFwTtwLD4WAnzHU9a7HIA/iHjWS12POMM9nU61WiVJVMYqUKkM
; i4mAfLgAsl8eX+bFNOBWqlEwiWHBieOC38VihnVtolFvwLEQHms/J5yyuGjo8ywwrQFa34lU2apApT
; QsELWCmwVmdXpb7eEQC6zCEGO6SmpYrNqAwTvjWCwWMvgO6zrvbVwSmLIAwONoyHgWQXg1lWkfsbSG
; xQSjMO0j1vTuSLtnHIxbqUTBqDiYxLAwx8KxECoOUCStT1kDi+sAno+GjGft7H6a1ncUVYbkUXrDAs
; F01er7iAeHOj3DwNyKRcHUcRBVGnjDCnSxBBwLx8KzbMra5E9Z/soO3E4ZADyOhoxnvdL1G2ey+5lC
; vRZ5qujJoyUMi71Q8FioVtxHbEB2xK1iTlepDWsqaFhNsRDBdzxlzfhTFgPwsLYD0RDzLDAtWt+Jp6
; JWgVrGsJhgLG6lfURYuwHQfStGFFSdruIaFg/e67FwtLGqgysOzVOWOBoyCE/rO/FUxH3EljMsUKvs
; IwJk/3hsWRO3giioY7rC/Aq33OuGhdruuNqAORaOhRi+Q8UBT1kYwPPRkPEsWN8hCJ/sWihKFaglDY
; up7E8peW9rm2cSYBaqUdC0YXngHXMsFAsxfMdTFrv9DNQcGIDnoyEzrefck0OC8OmvBVunrZY2LFBZ
; W8FvD3fUy6GswoCjoI44GMuw0EmhiGPVYyGC72FTlgfguWj4BkF4LdeC7bcmb3nDYipTK3hX/7OeKY
; i4lfbpSlBp4A0LDLNebRCAd+BYfCyE/cI5wZQVAPBrHw2als+zwLRofSe5bN5HJMNCKkMreNw9EeQh
; u2oUFE1XpgzrmoBj4VjI4PusYMrCAB5HQ8yzAMJvpvWdxLL11uRkWIIXqqitYIDsn25fGuRWMaNg7D
; gY07B48A4cSxQLGXxnFQfRlMUAPB8NmWm9SOs7qWVb8iDDClERW8Efji6vl0MXYkbBuHFQxbDqC9CC
; asN1WSzk4DsUSRtTVqPmMC2Lhh7PqkF4OjlMJ5uSBxmWREVqBb+zpU3Ire6lmK5MGhbPsVgsvODHQu
; hkhU1Zx9GUBQCedbMOCfpZwLNofUfPtWBDFYgMS0G2t4IPbFzlTSw8t1KNgkmmK/6EUMWwcLWhiWOF
; xMLTgimLLUZDzYEBeBwNeZ5FJ4f6lHcViAxLUba2gid8yM7KoQt+uzxpFEwyXfEtd96wmrpYHHjHHI
; vFQh6+nxJMWazmUO9m8dEQmdbLtL6jTXlWgciwYr5QNrWCYe3m6vgzDcge0ma3xrC4k0IG3nmOVY+F
; bMra3CiShk1ZAOBF0ZDxLAbhaX1HnzCQzyp5kGElkA1AHk4EPxxd4UP25FHwQQKzSmpYTSeFIRyLxU
; LWyTozHCyS8lMWBvBh0ZDxrN/T+o5WYSCfRfIgw0qovJ9S8t7WFU2Q/a4gCpqYrnQZFgPvjGOFxUIG
; 38OmLB7AQzcLR0OeZ9H6jplrgSUP+EA39b3IsFIqj1bw25vbA5Adc6s4UdAGw+I5VlgsZBWHpikLlU
; nr3SxRNCQIn8m1YDp5kGFpUJatYFi7YZAduBWuMMQB7WnMKo1hsWoDf1IYFQvZfuEcP2VxZVIRgBfx
; rJdpfcfYtWCyCkSGpVGmW8Fb13chyC7mVplOV1wHS2ZYC7xhhYB3WSxk8H02bMpiAF4QDXmexSA8re
; +YEa4C6UweZFiaZaoVzNZubnLcSlcUTBMH4xgWX224LuBYl7aJYyGrOLAi6fvclFWvOXAA/pCEZ724
; htZ3TF4LLHnArzquBTIsAzKxjzg3ujwA2TG3ynK60mVYIvDOc6x6LBTAd1YkZVPWDDdl1QG8Hw3xgv
; QbBOFzuRaAb6VNHmRYBqULQsLaDUwiPLdKGwWzMCx2m+QFroslAu88x8KxkK3qMPjOT1knuSkLd7NE
; 0RDzLDCtqe6nrHrvlPFagA9vuBbg2QpJrwUyLMNKCyFh7aYB2ZsrDHGjoGy6ysKwbisYFuZYLBby8B
; 1XHPgpiwfwsmiIIfwEnRwavxbSVoHIsDJSkn1EuLfV1YlnAtxKVxRMOl3pNCx2UsjAe4BjcbEwAN+5
; igM83p6fsuo1B4VoyCD8y2t+QxA+A6WpApFhZag4+4iwdjM/zpmVpMKQdLpKHAcFlQaZYYm6WDclHE
; sYCzn4rjRl+QCere00RUMBhKf1HfNKuo9IhpXDCxW1jwgnghiyi7gVHwUzj4MpDIuvNmDDUomFGL5L
; pywOwPPRMIxn0fpOdopbBSLDykkyIH9yZIUQsuuarrTEQQ2GFcWxWL1BFAvr8B1PWYNLAjf5EwJ4QT
; TkeRaY1t6ux+nkMCOpVoFgCiPDylGip5R4azc+ZNfFrXTFQRG/ErXcA4YlaLuLqg0yjiWMhbjiIJiy
; jnNTFgPwUdGwzrMIwudyLYRVgYD7wnVChmWBGIS8Njv9UxNk1xwF08TBrAyrzrFEsVAA31nFAU9ZJ0
; RTlkI0xDwLIPwore9kfi3wyYOdsoORkWFZoolNfb/ykF1XFNQ1XZkwLHZSKALvmGPhWMg6WRi+syKp
; aMoSAXjWzRJFwwCEp/WdzMVM6ptvvvnz119//W9gVtDdgn9GhmWBALKf27ZMCNllZpXbdJXQsFjbPe
; qkcD4iFmL4zvYLo6YsVnNgjwc7EhINRTzrgHtyuKG3q1DvqaIL4uF33333L99+++2/4ioQGZYFghNB
; Btl5bsVHQd3TVVrDeqDRsK4JOBauN7BYKILvqlOWEMBH8Cxa38lOPIDnq0BkWDlLCNn5NruGKKg1Dm
; o0rCiOhWPhJ6PN8D1YcYiYsgQAPiwaYp7FIDyt75gVMCswJr7igIE8GVZOgk+Oc4df+JmH7DqjoM44
; qMWwIqoNYYbF6g2hsRBNWR+Ipiy/TCoD8GHRkIfwdHKoX6r3kwMgT4aVg+CT5PYnc3+Fe1tFcas0UV
; BnHExqWF/GMCwVjiWKhRi+syJpYMoSlEkDAD4kGop41h9ofUer2Ak5mJXKmg4ZVoZipx93rn/249Wd
; Hb/emAwuNTdxqxRRUHccDDshTGpYUSeFAY6lEAsZfI8zZR0TdLNYNJTxrAN0Dy0twg9mpdUcywQREP
; old7+4+cO136//hYfsuqNgFtNVWMs9tmGFgHcRxwqLhWdiTFkiAC+LhjzPAtP63ZpFBOFTXgsMrMf5
; vWRYGQh/knz8XP8vwGqiuJWuKGiTYd1RMKxQjhURCzF8nwuZsmbQlMVqDgEAHxENeQi/t2sJmVZMYb
; Ce5Ok6ZFgGxR/RHhzqDNwuhudWsihoTRzUZFihJ4UhHAvXG8JiYaDiIJiyToZMWWw5WhYNRTyL1nfU
; BTgEgDqrJyT9OmRYhsQf0cIj5YOQneNWBqKgrukqS8MK41ihsRDDdzxlDalPWX9EAF4aDQU8CyD8aD
; et78jE9gBBaZ8QTYalWaIj2qG+2r2tbihwq7RRsGyGpRILz20Rw3dWJA2bssIAfL2bJeFZPISne2iJ
; hfcAdTzyiwxLo0RHtLV7W61wVCD7PUunK1OGhasN+KQwDLyHxUIM33HFQWnK2vBYE4BXiYYE4eXCYJ
; 3tAeoQGZYmhR3RvrOl1mTnuRVfYcBR0OrpKqVhLYQZVgh4nw+pN1xEsTAMvuOKg8qUJQLwOBo2VR04
; njXV/XSh3rOmBAbFrgUdT4zCIsNKKdkRLXtKcxO3UoyCaaarLOLgg5SGFXpSqMixLiDDCoPvuOIQnL
; KWCKcsDOCl0TDEtFr5adL8IZOJ70GGlULsk0R0RAtR8PxY4zbHpqNgHnFQp2El4VihsVAyZZ1EU9bx
; fnUAL4qGIp4Ft6Npxdsr40OmtGBdJjKsBAKQzj5Jwo5oj23pkEJ23VHQZsPCt0kOK4/yhqXCsWSx8L
; TClIUXo4M1B7VoGMazJruXFua9rONaYIdMusC6TGRYMaVyRAungtcnl9XNqolb7ZKblc7pymrD2qlm
; WPMJYmEAvieYsjCAZ9FQVnXgS6WtcGoIETDOHqAOkWHFkOoR7cxIhwvZObMyGAVNTlcmDYuvNuCTQg
; zeeY4VGgsl8D1QJN24JHLKwgBeORoinrWn+8nCvK+TCB8y6QbrMpFhKSjOES1MVzd8s0oSBdNOV4U2
; LEXwLouFuJOF4TuuOEinrDAArxgNMc8aKuGUlQVYl4kMK0Jxj2int3SGcysDUVB1utISByWVBlXDau
; pihRiWDLxflsRCGXwPFElDpixcc8AAHnezRNFQxLP2lmzKCrvBXpYiwwpRkk+SfvdkkDerBXShmo6C
; hTQs1MVKyrFwLJTBd+mUNRA2ZYVEQ0WeNViC29DgPUDZDfayEBmWQEk/SY4Mr/QuQBm3ymq6Mh0HZa
; XRJsOStN1VTwplHKspFobAd+mUxZVJQwF8RDTEPAvi4UTPcmvf5yrCh0xZgXWZyLCQVG/VGqZPJ1bU
; y6GmuVUW01XehiUD75hjyWIhv194SnHKCgB4hWgYxrNe7n60sL0s3XuAOkSG5SvurVp5bdvQ7U1XvF
; mptNlNT1dFMqzASaGEYzXHwqdCYyGG703rOopTFgbwUdGQN60tvSute7/LZGoPUIfIsKp6jmiPbFnp
; 3J4K51a6p6ss4mAmhiWpNvDgfT5hLOQrDrhIyk9ZMyFTFg/gD0dMWZhnTfUUp0jKDpnAsLKsK6iqpQ
; 0rza1aeV2eaPOY1UIGUTCXOBij0hBlWHg9R1ZtiOJY0lgoge+yKYtfjMYAPtDNUoiGjGe90LPEivd7
; 1LUQtb1hg1rWsNLeqhWrf11vs1mFRMGsp6uiGVYc8H45IhbiTtbZhFMWX3MIA/BR0bC/au+To9m1oO
; MGe6bVcoal61atWHsH1wTMKssoaGq6ytKwbkkMiwfvMo4VFQsxfJ9LOmUljIY2ciz2FCfbwLpMLWVY
; Om/VinVweJV7IS6v941UzMr26UqnYTXdsSFGFysOx+JjYTN8D1/XiTNlhQF4mWnt7LWLY2EcYkNdQV
; UtY1gmP0mOjqzyzOoux61MR8GyGpYMvEdxrKZYKIHvfJFUNmXxAF4lGmLT2tNrz8Mq8toD1KHSG1YW
; R7RntnfUDctkFMwyDkadEOo0LFm1IYpjRcVCvpPFVxxwkbR5ygqvOWAAz0dD0YL0gd78wXvee4A6VG
; rDMnmrVqxPJtqVzaoM01XUWk6UYUV2sWJyLD4WnpfEwrMxp6zjsikrRjR8uXdxZu97kWzYA9ShUhpW
; 1p8kn0+11XcETUXBUhtWxEkhb1jzKWMhhu98xYGfsvjFaCmAF0XDas20XutdZPx9L1La7Q3bVDrDyu
; pWrVif72zzzOpeSaarrA0rqtoQBd4vx4yF/H4hX3GQTVkyAM+v7RxihlWtTVlZvBex0m5v2KjSGFae
; R7S3kGGZMCsyLDl45zlWVCzk4XuaKYsH8E3RsNqYsrJ6P4LCnuJUdJXCsPI+or26o71mWHvMgPZWMC
; y+ixUF3qM4VlQs5OF7mimrCcCjaPhWxoalc3vDRhXesGw4omWGVZbpKhfDiqg2xOVYTbEwCr7HnLJk
; AB5HQzAvMKzXq+YZls7tDVtVWMOy6Yj208mOck9X++QdrCSGtRBlWDHBu0osPMfFQn6/cDZqyuLKpI
; GaAwfgWTQEwzrkGtYrVXOnhCa2N2xVIQ3LtiPaU9s7rZmusoiDJgwrqtqgwrGiYmEUfOcrDu/zU1ZE
; mZQH8GBWXjx09UL1CSPvPVPbG7aqUIZl6xHt9NZVRszK1jiYhWGpgHeeY0XFQhX4zhdJI6csCYDHpv
; V89Snt77ui7QHqUGEMCyYpW49oXxt+tn6hPjBoVkU2LP6+7gsxu1gi8B5VbxDGwgj4HnfKkgF44Fps
; wpqotmt7v9l8gz3TKoRh2f5JMrahpzZd7QmaTdbTVZENS1RtiAveRRwrKhYmmbJmoqasvkV1HVlXM6
; zh6mot77WstjdsldWGVaRPktu72lMblA3TVZEMS4VjXRyNjoWnmyoO3JS1MeaUhUzrbZiy1qW/r3sZ
; 9gB1yFrDYp8kEAOL8Ekyt32lUcN6kJFhPVQwrPsaDEupi6WBY6nEQh6+i4qkUVMWD+Cn1zemrJfWpn
; s+YVn2AHXIOsOCyFeEW7Xyet3lWLrYlVVxMEvDmopvWIlioWjK2iwvkvJT1knBlMVqDiwiMsPasTYZ
; v8KHTHBNFH0PUIesMqwiH9GO9fdkZlaZxsEcDSsJeFeNhXwn64zKlDWoNmWBYYGO+VPWQLU79vupjH
; uAOmSFYRXxVq0ifTzRWejpSoVfqbTchYal0HZXqTaocKwksVAE3xNNWRsahgWx8HBf/MJokW+wZ1q5
; G1aZjmhfHFqj3axa3bCawLsKx1KIhSL43lRxUJqywk3rj65hTa1Tj4Nl3wPUoVwNq2yfJAPw9Jzd7U
; 3GUpQ4mLthKZwUJuVYwljIw3dRxUFhymKL0V6pdMCvObg6un6xchxshT1AHcrFsMp8RHt4ZHViw7Ju
; utqXrNKgalh8211YbRBxrPH4HEsUC0WdLB6+80VS0ZTFFqPBsEDv9NcM6/d9yyLfL620B6hDmRtW2Y
; 9oh9f31KcsbCqmpquWNKyEHEslFooqDnyRVDRlzQwEDQumrIG18umq1fYAdSgzwyrbrVplYlMWNqoo
; 01KZrjKPgxYYlip45zlW0lgogu9RUxZ0tE4MNgzrXdewXlgvn65acQ9QhzIxrFY7ogWWdWd3e5PR2B
; wHTRuWcAE6YbXhuiLHShoLefguqjjgKcsrlW5cUjes6f4lodNVK+8B6pBxwyrrrVqjBEVSkdHonK5a
; xbCSgndRLLygEgsVKg6s/c4EhjXjT1m7+jqE74lW3wPUIWOGRUe0Vee838syZVg6zUr1hNC0YalUG5
; Q5VopYeFphyuJNC2Lh0f4nhNcC7QHqkRHDoiPamrb31wB8FHgvynSl2nJXNSzlLpYieBdxrEvbFGKh
; InzHUxbUHUC8YW1euyb0WiCwnl5aDYuOaJuFo2HR42AmhqV4UigC76ocSxQL+VUdIXz3pyxmVqD3Nz
; UMa/f6jsC1QGBdv7QZFh3RhuvD8ZVWw3abDEv5pDAFxxLFQlX4fmooaFgf+IZ1cOCZ+uud91Ocyiwt
; hkWfJHLBqeHlHR1Cs3pgwXRVRMMSgXcRxxLVG0SxUAW+A9ea29xsWDPuieH6tbX7XdEeoFmlMiw6ol
; UX41kiw3pAhpXIsJQ5lmoslMB3+LX210HDOrHxCWd43RoC6xkpsWHREW18YdOSGVTWZmWbYalWG65N
; mI+FAN+ZWXmG5eoUMq3RvmfpBnsZKrZh0SdJOsEdHcC0eLOC+8E/tGm62qfWwUprWAuqhpUCvKeJhT
; B18YbFYuH+TT0ts71hi2IZFh3R6hGcHN5G8fC+/3gwbAw2xsGsDEu12nA9BscS1RuiYiH8NeiMwLAO
; 7x2lG+zlICXD4m/VSmA9veqT1p5mw6rLsjiYp2HFAe+qHEsYC33Twjq75cmAYX367pstub1hgyINi2
; 7Vak47B7q9p+2IDAvMoWYm5TEs0W2SFxS7WHHAu5BjKcZCmLpEhgVT1rmx5b8uXD5HOCRHVWTAnI5o
; zQueaXh9Z0dTJHy4t40zldYxrDgnhWk5FouF8CsTP2WBYX00tuLXLy59/Be6wV6+qsALwE9OBNazVf
; +6XmdufGWAX/GGZVJFMaybioYVyrFCYiE2K5FhXdi77peFa5/9SNsb+auCTzkgj9MRbT4C0/rT6OpQ
; w2JGkolZ7VOvNKQ1rDhdrJspOVZYveECmrDOc4Z15cj+n2l7wx55DAtM6vbt2//5/fff/zO8OGBidE
; Sbj4Brwb20sGE9bEHDUq02hBmWaiwEw/oEDGtr0LBAN2aP/kRg3S55hgWfHt98882f/8n9H4uBZFj5
; CVZ5TrsRUWQovOH8w/7WMay04P1KmGGxKWtrzbAu7u/75R8ffvnv1K+yTxW8BwjsCswK4iCB9vz10u
; Y1zp09HZGGxaTNsARmFaflHmpYMdrucaoNURzrCtIlgWFdRIZ1c/aYN1UBWIfkAdcC4RF7VBHtAcKL
; BTuCDMjTJ0x+gmnrHZdtMeOSGVYS4yqzYV3hzKrGscSGNf/mzr/d/eLmD/whE38ARddCvgqtNeD7+T
; AgX5Q/VBm1c7Db+WyqU2g6vFnFMS9rDSvGSSHmWBAPmebHOcNyzYo3rDvHXKh+/bMfZVMUXAtU8bFD
; kcVR4FtsLKaTkvy1yzWuK5xx8eYkmrpE5vXQEsMStd3jnBTenFwWMCqPaUkMC2LhmfGVv97+aCbWHi
; CfPIrwfimblFZz4BOF1R9g6qKxOH9h4xKZkWzqwn/fRAfLpGGxWAgmxXRDZFiuWfGGBWY1O7Lcmd6/
; LfH2Bv+4Okoe2Up5+ZmNxQzIE4S0Q6KJSzR1iUwrdOKyzLDgxJCpFguDujFR41gywzo5ssLZP7Ba21
; OcCMjno9i3lyEgb6fAuADO33XhvOrUFYdpGTWsXQ2TWkDCRoUN6wZnWNcFhjXvG9bBoU5naF2Pkac4
; EZDPXolu4IchJI3FdglOFZ/b1OVNXcy8ZFOX2LDamkwr9J70e5qFDevenoZYF4vXnV1Bo1pAXawww7
; ohMazjI+3Oc4Or6/9NTD7FiU8eBOTNKtUtktmdHAhC2ikwryMjz9bNS92s2pTM6oE/YYkM6x5nVnEN
; C2oNIN6sWCS8gQRm9cHWNue1oZXOUF9P/c+f5VOcKHlko9QPoeAhJL1QdgrMC4qo74+tapq8glFQ3b
; DuazAsMKvYhuVPWTNbO5yXNq12+tf2Nv1583iKE1WBzEvbY74IQhZHYF7AvN7Yssa5MLnSM7Bmw2qL
; NCvMsLBZ1Q1rd9CsVA3r9pTYsE66BvXG5lXOZH+X9M+X91OcqApkTlofpEoQsriCB2QA+4IIeX6y0y
; upyqKgScO6NNHmvDfa6bzpmtPewTXOZhTzot5/tjzFiapAZqT9UfXUCi6PYBLzjGxjl3cferj9DTwU
; 9uOJTufSjg7vvvRwx1TRKWHdsLiTws+n2pwrO9qds9s7nA/GOp1jI6ucg8OrnH2uMe2ImJxksvEpTl
; QF0q+KqS9MreDWEdzLCzS8vqehvobgn5n63kW42SQBeX2qmPzi1AommVSRnuLEV4EoeSTT/wNVoy5f
; 9y2AHwAAAABJRU5ErkJggg==
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

;End of Gcode
; filament used [mm] = 128.84
; filament used [cm3] = 0.31
; filament used [g] = 0.39
; filament cost = 0.01
; total filament used [g] = 0.39
; total filament cost = 0.01
; estimated printing time (normal mode) = 6m 2s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,320x0,320x350,0x350
; bed_temperature = 50
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 60
; brim_width = 0
; clip_multipart_objects = 0
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.1
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = ;End GCode begin\nM104 S0 ;extruder heater off\nM140 S0 ;heated bed heater off (if you have it)\nG90 ;absolute positioning\nG92 E0\nG1 E-2 F300 ;retract the filament a bit before lifting the nozzle, to release some of the pressure\nG1 Z330 E-1 F3000 ;move Z up a bit and retract filament even more\nG1 X0 F3000 ;move X to min endstops, so the head is out of the way\nG1 Y350 F3000 ;so the head is out of the way and Plate is moved forward\nM84 ;steppers off\n;End GCode end\nM82 ;absolute extrusion mode\nM104 S0\nM107\n;End of Gcode
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 15
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 60
; filament_colour = #00FF00
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 30
; filament_density = 1.25
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Snapmaker PLA"
; filament_soluble = 0
; filament_spool_weight = 1000
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 0
; first_layer_bed_temperature = 50
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 18
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 27%
; infill_speed = 50
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.15
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1000,1250
; machine_max_acceleration_retracting = 1000,1250
; machine_max_acceleration_x = 1000,1000
; machine_max_acceleration_y = 1000,1000
; machine_max_acceleration_z = 100,200
; machine_max_feedrate_e = 25,120
; machine_max_feedrate_x = 150,200
; machine_max_feedrate_y = 150,200
; machine_max_feedrate_z = 50,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_height = 330
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 60
; min_layer_height = 0.05
; min_print_speed = 10
; min_skirt_length = 25
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 20
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = Snapmaker 2.0 A350
; printer_model = 
; printer_notes = 
; printer_settings_id = Snapmaker 2 A350 Slow Accel
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 5
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 328
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = rear
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 2
; skirts = 3
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = M82 ;absolute extrusion mode\n;Start GCode begin\nM140 S[first_layer_bed_temperature]   ;Start Warming Bed\nM104 S160 ;Preheat Nozzle\nM425 F1 S0 X0.12 Y0.02 Z0.02 ; Backlash Compensation\nM92 E247.74 ; Set new extruder steps/mm\nM900 K0.055 ; set K-factor\nG28 ; home all axes\nG90 ;absolute positioning\nG1 X-10 Y-10 F3000\nG1 Z0 F1800\nG1 Z5 F5000 ; lift nozzle\nM190 S[first_layer_bed_temperature]   ;Wait For Bed Temperature\nM109 S[first_layer_temperature] ;Wait for Hotend Temperature\nG92 E0\nG1 E20 F200\nG92 E0\n;Start GCode end\nG1 F3600 E-5
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.16
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thin_walls = 1
; threads = 8
; thumbnails = 300x150
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 15
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_speed = 70
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
_END
)

while true; do
	x="${tpl}"
	for i in $(seq 1 1 $((${RANDOM} % 64))); do
		rnd=$((${RANDOM} % ${#x}))
		x="${x:0:${rnd}}$(head -c 1 /dev/urandom)${x:${rnd}}"
	done
	echo -n -E "${x}" > "fuzz.dat"
	../bin/sm2pspp "fuzz.dat" 2>&1 | grep -v "Warning"
	grep -q "post-processed by sm2pspp" "fuzz.dat" || exit 1
done
